---
title: "Análise Completa dos Dados Neurocognitivos"
author: "Rodolpho Cortez, Felipe Fagundes"
output: html_notebook
date: "2024-05-06"
---
```{=html}
<style type="text/css">
.main-container {
  max-width: 85%;
  margin-left: auto;
  margin-right: auto;
}
</style>
```

```{r Box-plots }

knitr::opts_chunk$set(
  message=FALSE, 
  warning=FALSE,
  fig.cap= "Box Plots Test-T")


#install.packages("ggtext")

library(dplyr)
library(ggplot2)
library(readxl)
library(tidyr)
library(ggpubr)
library(ggtext)


getwd()

list.files()

data <- readxl::read_excel("Cópia de DADOS_BRUTOS_COVID_LONGA_SEQUENCIAMENTO.xlsx")

data <- na.omit(data)

data

#######################################    Test.T BPAs #############################################

p1 <- data %>%  select(GROUP , BPA_CONC_POINTS,BPA_DIVID_POINTS, BPA_ALTERN_POINTS )


     # Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

p1_long <- tidyr::pivot_longer(p1, cols = -GROUP, names_to = "Variable", values_to = "Value")


                                    #Gráfico facetado BPA-Conc,Divid,Altern.

plot1 <- ggplot(p1_long, aes(x = GROUP, y = Value, fill = GROUP)) + 
        
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 2.5, width = 0.15, alpha = 0.5) +
  
  labs(x = NULL, y = NULL) + 
  
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  
  facet_wrap(~ Variable, scales = "free_y", 
             labeller = labeller(Variable = 
                                   c(BPA_CONC_POINTS = "Conc Points",
                                     BPA_DIVID_POINTS = "Divid Points",
                                     BPA_ALTERN_POINTS = "Altern Points"))) +
  
  scale_y_continuous(limits = c(20, 130), breaks = seq(20, 120, by = 20)) +
  
  theme(axis.text = element_text(size = 20, color = "black"),
        axis.title = element_text(size = 25, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 20,  face = "bold"),
        text = element_text(size = 20),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14,  face = "bold"))


                            #  Test-T

plot1 <- plot1 + stat_compare_means(method = "t.test", label.x = 1.38)

plot1

ggsave("bxplot_BPAs.pdf", plot = plot1, width = 13, height = 10)



                                    #BPA Total

ptotal <- data %>%  select(GROUP ,BPA_TOTAL)

# Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

#p_bpa<- tidyr::pivot_longer(ptotal, cols = -GROUP, names_to = "Variable", values_to = "Value")


                                    
plototal <- ggplot(ptotal, aes(x = GROUP, y = BPA_TOTAL, fill = GROUP)) + 
  
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 2.5, width = 0.15, alpha = 0.5) +
  
  labs(x = NULL, y = NULL) + 
  ggtitle("Total Score") +
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  
  scale_y_continuous(limits = c(100, 400), breaks = seq(100, 400, by = 50)) +
  
  theme(axis.text = element_text(size = 20, color = "black"),
        axis.title = element_text(size = 25, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 20,  face = "bold"),
        text = element_text(size = 20),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14,  face = "bold"))


                            #  Test-T

plototal <- plototal + stat_compare_means(method = "t.test", label.x = 1.38)

plototal

ggsave("bxplot_BPAsTOTAL.pdf", plot = plototal, width = 13, height = 10)


#######################################    Test.T FDTs #############################################


data <- readxl::read_excel("Cópia de DADOS_BRUTOS_COVID_LONGA_SEQUENCIAMENTO.xlsx")

data <- na.omit(data)

data

                                      #Filtrando FDTs

p2 <- data %>%  select(GROUP , FDT_READING_TIME ,FDT_COUNTING_TIME, FDT_CHOOSING_TIME, FDT_CHANGING_TIME,
                       FDT_INHIBITION, FDT_FLEXIBILITY )


     # Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

p2_long <- tidyr::pivot_longer(p2, cols = -GROUP, names_to = "Variable", values_to = "Value")


                                          # P2

plot2 <- ggplot(p2_long, aes(x = GROUP, y = Value, fill = GROUP)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 1.5, width = 0.15, alpha = 0.5) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  facet_wrap(~ Variable, scales = "free_y", 
             labeller = labeller(Variable = 
                                   c(FDT_READING_TIME = "Reading Time",
                                     FDT_COUNTING_TIME = "Counting Time",
                                     FDT_CHOOSING_TIME = "Choosing Time",
                                     FDT_CHANGING_TIME = "Chaging Time",
                                     FDT_INHIBITION =  "Inhibition", 
                                     FDT_FLEXIBILITY = "Flexibility"))) +
  #scale_y_continuous(limits = c(20, 130), breaks = seq(20, 100, by = 20)) +
  theme(axis.text = element_text(size = 15, color = "black"),
        axis.title = element_text(size = 19, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 1.5, face = "bold"),
        text = element_text(size = 12, family = ""),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"))


# Ajuste as escalas de acordo com o mínimo e máximo dos dados
#plot1 <- plot1 + ylim(min(p1_long$Value), max(p1_long$Value))

plot2 <- plot2 + stat_compare_means(method = "t.test" )
 
plot2

ggsave(filename = "FDTs_values.pdf", plot = plot2)


#######################################     Test.T RAVLTs #############################################



data <- readxl::read_excel("Cópia de DADOS_BRUTOS_COVID_LONGA_SEQUENCIAMENTO.xlsx")

data <- na.omit(data)

data

                                      #Filtrando RAVLTs


p3 <- data %>%  select(GROUP , RAVLT_A1 ,RAVLT_A2, RAVLT_A3, RAVLT_A4   )

p4 <- data %>%  select(GROUP , RAVLT_A5, RAVLT_A6, RAVLT_A7)

p5 <- data %>%  select(GROUP , RAVLT_TOTALSCORE)

p6 <- data %>%  select(GROUP,RAVLT_B1,RAVLT_REC,RAVLT_RETENTION)

p7 <- data %>%  select(GROUP,RAVLT_RETENTION,RAVLT_RETRO_INTERFERENCE)



     # Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

p3_long <- tidyr::pivot_longer(p3, cols = -GROUP, names_to = "Variable", values_to = "Value")


                                          # P3

plot3 <- ggplot(p3_long, aes(x = GROUP, y = Value, fill = GROUP)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 1.5, width = 0.15, alpha = 0.5) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  facet_wrap(~ Variable, scales = "free_y", 
             labeller = labeller(Variable = 
                                   c(RAVLT_A1 = "RAVLT_A1",
                                     RAVLT_A2 = " RAVLT_A2",
                                     RAVLT_A3 = "RAVLT_A3",
                                     RAVLT_A4 = "RAVLT_A4"))) +
  scale_y_continuous(limits = c(0, 20)) +
  theme(axis.text = element_text(size = 11, color = "black"),
        axis.title = element_text(size = 15, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 14, face = "bold"),
        text = element_text(size = 12,),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"))



plot3 <- plot3 + stat_compare_means(method = "t.test" , label.y = 18, label.x = 1.1)

plot3

ggsave(filename = "RAVLT_values.pdf", plot = plot3)



     # Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

p4_long <- tidyr::pivot_longer(p4, cols = -GROUP, names_to = "Variable", values_to = "Value")


                                          # P4

plot4 <- ggplot(p4_long, aes(x = GROUP, y = Value, fill = GROUP)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 1.5, width = 0.15, alpha = 0.5) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  facet_wrap(~ Variable, scales = "free_y", 
             labeller = labeller(Variable = 
                                   c(RAVLT_A5 = "RAVLT_A5",
                                     RAVLT_A6 = " RAVLT_A6",
                                     RAVLT_A7 = "RAVLT_A7"))) +
  scale_y_continuous(limits = c(0, 20)) +
  theme(axis.text = element_text(size = 11, color = "black"),
        axis.title = element_text(size = 15, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 14, face = "bold"),
        text = element_text(size = 12,),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"))


# Ajuste as escalas de acordo com o mínimo e máximo dos dados
#plot1 <- plot1 + ylim(min(p1_long$Value), max(p1_long$Value))

plot4 <- plot4 + stat_compare_means(method = "t.test" , label.y = 18, label.x = 1.1)

plot4

ggsave(filename = "RAVLT_A5_A7.pdf", plot = plot4)



     # Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

p5_long <- tidyr::pivot_longer(p5, cols = -GROUP, names_to = "Variable", values_to = "Value")

                                          # P5

plot5 <- ggplot(p5_long, aes(x = GROUP, y = Value, fill = GROUP)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 1.5, width = 0.15, alpha = 0.5) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  facet_wrap(~ Variable, scales = "free_y", 
             labeller = labeller(Variable = 
                                   c(RAVLT_TOTALSCORE = "RAVLT_TOTALSCORE"))) +
  #scale_y_continuous(limits = c(0, 20)) +
  theme(axis.text = element_text(size = 11, color = "black"),
        axis.title = element_text(size = 15, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 14, face = "bold"),
        text = element_text(size = 12, ),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"))


# Ajuste as escalas de acordo com o mínimo e máximo dos dados
#plot1 <- plot1 + ylim(min(p1_long$Value), max(p1_long$Value))

plot5 <- plot5 + stat_compare_means(method = "t.test" ,  label.y = 65, label.x =1.7)

plot5

ggsave(filename = "RAVLT_total.pdf", plot = plot5)




     # Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

p6_long <- tidyr::pivot_longer(p6, cols = -GROUP, names_to = "Variable", values_to = "Value")

                                          # P6

plot6 <- ggplot(p6_long, aes(x = GROUP, y = Value, fill = GROUP)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 1.5, width = 0.15, alpha = 0.5) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  facet_wrap(~ Variable, scales = "free_y", 
             labeller = labeller(Variable = 
                                   c(RAVLT_B1 = "RAVLT_B1",
                                     RAVLT_REC = " RAVLT_REC"
                                     ))) +
  #scale_y_continuous(limits = c(0, 20)) +
  theme(axis.text = element_text(size = 11, color = "black"),
        axis.title = element_text(size = 15, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 14,  face = "bold"),
        text = element_text(size = 12),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"))


# Ajuste as escalas de acordo com o mínimo e máximo dos dados
#plot1 <- plot1 + ylim(min(p1_long$Value), max(p1_long$Value))

plot6 + stat_compare_means(method = "t.test", label.y = 15, label.x = 1.1)

plot6

ggsave(filename = "RAVLT_B1-RAVLT_REC.pdf", plot = plot6)


     # Reorganizar os dados para o formato 'long' usando a função pivot_longer() do pacote tidyr

p7_long <- tidyr::pivot_longer(p7, cols = -GROUP, names_to = "Variable", values_to = "Value")


                                          # P7

plot7 <- ggplot(p7_long, aes(x = GROUP, y = Value, fill = GROUP)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.5, width = 0.7, coef = 0, lwd = 0.4, color = "black") +
  geom_jitter(aes(color = GROUP), size = 1.5, width = 0.15, alpha = 0.5) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(values = c("#1a2887", "#799de4")) +  
  scale_color_manual(values = c("#1a2887", "#799de4")) +
  facet_wrap(~ Variable, scales = "free_y", 
             labeller = labeller(Variable = 
                                   c(
                                     RAVLT_RETENTION = "RAVLT_RETENTION",
                                     RAVLT_RETRO_INTERFERENCE = "RAVLT_RETRO_INTERFERENCE"))) +
  scale_y_continuous(limits = c(0, 2)) +
  theme(axis.text = element_text(size = 11, color = "black"),
        axis.title = element_text(size = 15, color = "black"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),
        plot.title = element_text(size = 14, face = "bold"),
        text = element_text(size = 12),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14, face = "bold"))


plot7 + stat_compare_means(method = "t.test" )

plot7

ggsave(filename = "RAVLT_RETENTION-RAVLT_RETRO_INTERFERENCE.pdf", plot = plot7)


```

```{r Calculating}

library(tibble)
library(readxl)
library(dplyr)
library(gtExtras)
library(ggplot2)
library(plotly)
library(viridis)
library(hrbrthemes)
library(openxlsx)


#data <- readxl::read_xlsx ("BPAs_FDTs_ RAVLTs_EscoreZ.xlsx", sheet = 1)


#install.packages("tibble")
#install.packages("openxlsx")




#setwd("C:/Users/User/Desktop/Analysis in R/NeuroCovid")

getwd()


data <- readxl::read_xlsx ("Cópia de DADOS_BRUTOS_COVID_LONGA_SEQUENCIAMENTO.xlsx")

data <- na.omit(data)

 
################################## BPA Z-Score   #####################################



                                # 1º Try
                  # TENTATIVA DE CRIAÇÃO DE FUNÇÃO

#cbind(data)
#
#calcular_z_score <- function(x, media, desvio_padrao) {
#  if (x >= 21 & x <= 30) {
#    z_score <- (x - media) / desvio_padrao
#    return(z_score)
#  }
#}


                                # 2º Try

## Definir os valores constantes de média e desvio padrão para cada faixa etária
#constantes <- tribble(
#  ~LIMIT_AGE, ~media_constante, ~desvio_padrao_constante,
#  "18-20", 85.79, 22.53,
#  "21-30", 87.08, 21.50,
#  "31-40", 85.48, 22.56,
#  "41-49", 80.72, 22.85
#)

                                # 3º Try
  # COMEÇAR DAQUI ----->  DETERMINANDO LIMITES A SEREM APLICADOS

limites_idade <- c(18, 20, 30, 40, 50)


data <- data %>%
  mutate(LIMIT_AGE = cut(AGE, breaks = limites_idade, labels =
                           c("18-20", "21-30", "31-40", "41-50"))) %>% 
  arrange(AGE)
  
data

# Calcular o Z-score usando as constantes para cada faixa etária


#BPA_CONC

BPA_CONC_EscoreZ <- data %>%
  mutate(BPA_CONC_EscoreZ = case_when(
    LIMIT_AGE == "18-20" ~ (BPA_CONC_POINTS - 85.79) / 22.53,
    LIMIT_AGE == "21-30" ~ (BPA_CONC_POINTS - 87.08) / 21.50,
    LIMIT_AGE == "31-40" ~ (BPA_CONC_POINTS - 85.48) / 22.56,
    LIMIT_AGE == "41-50" ~ (BPA_CONC_POINTS - 80.72) / 22.85,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID, AGE,GROUP,EDU_LEVEL, LIMIT_AGE,BPA_CONC_POINTS, BPA_CONC_EscoreZ) %>% 
  arrange(ID)

BPA_CONC_EscoreZ


#BPA_DIVD

BPA_DIVID_EscoreZ <- data %>%
  mutate(BPA_DIVID_EscoreZ = case_when(
    LIMIT_AGE == "18-20" ~ (BPA_DIVID_POINTS - 79.42) / 23.49,
    LIMIT_AGE == "21-30" ~ (BPA_DIVID_POINTS - 77.19) / 24.42,
    LIMIT_AGE == "31-40" ~ (BPA_DIVID_POINTS - 71.28) / 25.33,
    LIMIT_AGE == "41-50" ~ (BPA_DIVID_POINTS - 61.22) / 26.53,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,BPA_DIVID_POINTS, BPA_DIVID_EscoreZ) %>% 
  arrange(ID)

BPA_DIVID_EscoreZ


#BPA_ALTERN

BPA_ALTERN_EscoreZ <- data %>%
  mutate(BPA_ALTERN_EscoreZ = case_when(
    LIMIT_AGE == "18-20" ~ (BPA_ALTERN_POINTS - 93.21) / 21.76,
    LIMIT_AGE == "21-30" ~ (BPA_ALTERN_POINTS - 87.53) / 23.56,
    LIMIT_AGE == "31-40" ~ (BPA_ALTERN_POINTS - 82.28) / 24.84,
    LIMIT_AGE == "41-50" ~ (BPA_ALTERN_POINTS - 72.70) / 25.80,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,BPA_ALTERN_POINTS, BPA_ALTERN_EscoreZ) %>% 
  arrange(ID)

BPA_ALTERN_EscoreZ 


#BPA_TOTAL

BPA_TOTAL_EscoreZ <- data %>%
  mutate(BPA_TOTAL_EscoreZ = case_when(
    LIMIT_AGE == "18-20" ~ (BPA_TOTAL - 258.42) / 56.59,
    LIMIT_AGE == "21-30" ~ (BPA_TOTAL - 251.79) / 58.61,
    LIMIT_AGE == "31-40" ~ (BPA_TOTAL - 239.04) / 62.77,
    LIMIT_AGE == "41-50" ~ (BPA_TOTAL - 214.65) / 64.33,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>% 
  select(ID, BPA_TOTAL, BPA_TOTAL_EscoreZ) %>% 
  arrange(data$ID)
  

BPA_TOTAL_EscoreZ



BPAs_EscoreZ <- bind_cols(BPA_CONC_EscoreZ, BPA_DIVID_EscoreZ, BPA_ALTERN_EscoreZ, BPA_TOTAL_EscoreZ) %>% 
          na.omit()

write.xlsx(BPAs_EscoreZ, file = "BPAs_EscoreZ.xlsx")




################################## FDT Z-Score   #####################################


data <- readxl::read_xlsx ("Cópia de DADOS_BRUTOS_COVID_LONGA_SEQUENCIAMENTO.xlsx")

data <- na.omit(data)


                # DETERMINANDO LIMITES A SEREM APLICADOS

limites_idade <- c(18, 19, 34, 50)

                # ADICIONANDO COLUNA AO DADO, RELACIONADO AOS LIMITES DESEJADOS

data <- data %>%
  mutate(LIMIT_AGE = cut(AGE, breaks = limites_idade, labels =
                           c("18", "19-34", "35-50"))) %>% 
  arrange(AGE)
  
data


#FDT READING

FDT_READING_TIME_Z <- data %>%
  mutate(FDT_READING_TIME_Z = case_when(
    LIMIT_AGE == "18" ~ (FDT_READING_TIME - 20.4) / 4.1,
    LIMIT_AGE == "19-34" ~ (FDT_READING_TIME - 22) / 5.6,
    LIMIT_AGE == "35-50" ~ (FDT_READING_TIME - 23.9) / 6.5,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,AGE, EDU_LEVEL,GROUP, LIMIT_AGE,FDT_READING_TIME,  FDT_READING_TIME_Z) %>% 
  arrange(ID)


FDT_READING_TIME_Z



#FDT COUTING

FDT_COUNTING_TIME_Z <- data %>%
  mutate(FDT_COUNTING_TIME_Z = case_when(
    LIMIT_AGE == "18" ~ (FDT_COUNTING_TIME - 23.8) / 3.5,
    LIMIT_AGE == "19-34" ~ (FDT_COUNTING_TIME - 24.2) / 5.2,
    LIMIT_AGE == "35-50" ~ (FDT_COUNTING_TIME - 27.1) / 7.2,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,FDT_COUNTING_TIME, FDT_COUNTING_TIME_Z) %>% 
  arrange(ID)


FDT_COUNTING_TIME_Z


#FDT CHOOSING

FDT_CHOOSING_TIME_Z <- data %>%
  mutate(FDT_CHOOSING_TIME_Z = case_when(
    LIMIT_AGE == "18" ~ (FDT_CHOOSING_TIME - 34) / 5.9,
    LIMIT_AGE == "19-34" ~ (FDT_CHOOSING_TIME - 36.9) / 10,
    LIMIT_AGE == "35-50" ~ (FDT_CHOOSING_TIME - 41.7) / 14.5,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,FDT_CHOOSING_TIME, FDT_CHOOSING_TIME_Z) %>% 
  arrange(ID)


FDT_CHOOSING_TIME_Z



#FDT CHANGING

FDT_CHANGING_TIME_Z <- data %>%
  mutate(FDT_CHANGING_TIME_Z = case_when(
    LIMIT_AGE == "18" ~ (FDT_CHANGING_TIME - 44.8) / 9.1,
    LIMIT_AGE == "19-34" ~ (FDT_CHANGING_TIME - 46) / 13,
    LIMIT_AGE == "35-50" ~ (FDT_CHANGING_TIME - 53.6) / 18.4,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,FDT_CHANGING_TIME, FDT_CHANGING_TIME_Z) %>% 
  arrange(ID)


FDT_CHANGING_TIME_Z




#FDT INHIBITION

FDT_INHIBITION_Z <- data %>%
  mutate(FDT_INHIBITION_Z = case_when(
    LIMIT_AGE == "18" ~ (FDT_INHIBITION - 13.6) / 4.9,
    LIMIT_AGE == "19-34" ~ (FDT_INHIBITION - 14.8) / 8.3,
    LIMIT_AGE == "35-50" ~ (FDT_INHIBITION - 17.8) / 12,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,FDT_INHIBITION, FDT_INHIBITION_Z) %>% 
  arrange(ID)


FDT_INHIBITION_Z




#FDT FLEXBILITY

FDT_FLEXIBILITY_Z <- data %>%
  mutate(FDT_FLEXIBILITY_Z = case_when(
    LIMIT_AGE == "18" ~ (FDT_FLEXIBILITY - 24.4) / 7.8,
    LIMIT_AGE == "19-34" ~ (FDT_FLEXIBILITY - 23.9) / 10.8,
    LIMIT_AGE == "35-50" ~ (FDT_FLEXIBILITY - 29.7) / 15.7,
    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,FDT_FLEXIBILITY, FDT_FLEXIBILITY_Z) %>% 
  arrange(ID)


FDT_FLEXIBILITY_Z



#BIND COLS E SALVAR

FDT_EscoreZ <- bind_cols(FDT_READING_TIME_Z,FDT_COUNTING_TIME_Z,FDT_CHOOSING_TIME_Z,
                         FDT_CHANGING_TIME_Z,FDT_INHIBITION_Z,FDT_FLEXIBILITY_Z)



write.xlsx(FDT_EscoreZ, file = "FDT_EscoreZ.xlsx")



################################## RAVLTS Z-Score  #####################################

data <- readxl::read_xlsx ("Cópia de DADOS_BRUTOS_COVID_LONGA_SEQUENCIAMENTO.xlsx")

data <- na.omit(data)



limites_idade <- c(18, 20, 30, 40, 50)


data <- data %>%
  mutate(LIMIT_AGE = 
           cut(AGE, breaks = limites_idade, labels = 
                 c("18-20", "21-30", "31-40", "41-50"))) %>% 
  arrange(AGE) 
  
data


#RAVLT A1

RAVLT_A1_Z <- data %>%
  mutate(RAVLT_A1_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_A1 - 6.8) / 1.7,
    LIMIT_AGE == "21-30" ~ (RAVLT_A1 - 6.5) / 1.7,
    LIMIT_AGE == "31-40" ~ (RAVLT_A1 - 6.1) / 1.6,
    LIMIT_AGE == "41-50" ~ (RAVLT_A1 - 6) / 1.6,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID, AGE,EDU_LEVEL,GROUP, LIMIT_AGE,RAVLT_A1,  RAVLT_A1_Z) %>% 
  arrange(ID)


RAVLT_A1_Z 




#RAVLT A2

RAVLT_A2_Z <- data %>%
  mutate(RAVLT_A2_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_A2 - 9.5) / 2.2,
    LIMIT_AGE == "21-30" ~ (RAVLT_A2 - 8.9) / 2.2,
    LIMIT_AGE == "31-40" ~ (RAVLT_A2 - 8.7) / 2,
    LIMIT_AGE == "41-50" ~ (RAVLT_A2 - 8.5) / 2,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_A2, RAVLT_A2_Z) %>% 
  arrange(ID)


RAVLT_A2_Z


#RAVLT A3

RAVLT_A3_Z <- data %>%
  mutate(RAVLT_A3_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_A3 - 11) / 2.2,
    LIMIT_AGE == "21-30" ~ (RAVLT_A3 - 10.4) / 2.4,
    LIMIT_AGE == "31-40" ~ (RAVLT_A3 - 10.3) / 2.1,
    LIMIT_AGE == "41-50" ~ (RAVLT_A3 - 9.8) / 2.5,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_A3, RAVLT_A3_Z) %>% 
  arrange(ID)


RAVLT_A3_Z



#RAVLT A4

RAVLT_A4_Z <- data %>%
  mutate(RAVLT_A4_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_A4 - 11.8) / 2.4,
    LIMIT_AGE == "21-30" ~ (RAVLT_A4 - 11.4) / 2.4,
    LIMIT_AGE == "31-40" ~ (RAVLT_A4 - 11.4) / 2.1,
    LIMIT_AGE == "41-50" ~ (RAVLT_A4 - 10.7) / 2.7,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_A4,RAVLT_A4_Z) %>% 
  arrange(ID)


RAVLT_A4_Z





#RAVLT A5

RAVLT_A5_Z <- data %>%
  mutate(RAVLT_A5_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_A5 - 12.2) / 2.4,
    LIMIT_AGE == "21-30" ~ (RAVLT_A5 - 12.2) / 2.2,
    LIMIT_AGE == "31-40" ~ (RAVLT_A5 - 12.2) / 2.2,
    LIMIT_AGE == "41-50" ~ (RAVLT_A5 - 11.7) / 2.6,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_A5, RAVLT_A5_Z) %>% 
  arrange(ID)


RAVLT_A5_Z




#RAVLT  B1

RAVLT_B1_Z <- data %>%
  mutate(RAVLT_B1_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_B1 - 6.3) / 1.8,
    LIMIT_AGE == "21-30" ~ (RAVLT_B1 - 5.7) / 1.8,
    LIMIT_AGE == "31-40" ~ (RAVLT_B1 - 5.3) / 1.6,
    LIMIT_AGE == "41-50" ~ (RAVLT_B1 - 4.9) / 1.6,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_B1, RAVLT_B1_Z) %>% 
  arrange(ID)


RAVLT_B1_Z



#RAVLT A6

RAVLT_A6_Z <- data %>%
  mutate(RAVLT_A6_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_A6 - 11.1) / 2.5,
    LIMIT_AGE == "21-30" ~ (RAVLT_A6 - 10.9) / 2.6,
    LIMIT_AGE == "31-40" ~ (RAVLT_A6 - 10.8) / 2.4,
    LIMIT_AGE == "41-50" ~ (RAVLT_A6 - 9.8) / 2.8,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_A6, RAVLT_A6_Z) %>% 
  arrange(ID)


RAVLT_A6_Z


#RAVLT A7

RAVLT_A7_Z <- data %>%
  mutate(RAVLT_A7_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_A7 - 11) / 2.7,
    LIMIT_AGE == "21-30" ~ (RAVLT_A7 - 10.7) / 2.7,
    LIMIT_AGE == "31-40" ~ (RAVLT_A7 - 10.3) / 2.4,
    LIMIT_AGE == "41-50" ~ (RAVLT_A7 - 9.6) / 2.8,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_A7,RAVLT_A7_Z) %>% 
  arrange(ID)


RAVLT_A7_Z



#RAVLT REC

RAVLT_REC_Z <- data %>%
  mutate(RAVLT_REC_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_REC - 10) / 5.7,
    LIMIT_AGE == "21-30" ~ (RAVLT_REC - 11.4) / 4.7,
    LIMIT_AGE == "31-40" ~ (RAVLT_REC - 11.1) / 4.7,
    LIMIT_AGE == "41-50" ~ (RAVLT_REC - 9.9) / 5.6,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_REC,RAVLT_REC_Z) %>% 
  arrange(ID)


RAVLT_REC_Z



#RAVLT_TOTALSCORE


RAVLT_TOTALSCORE_Z <- data %>%
  mutate(RAVLT_TOTALSCORE_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_TOTALSCORE - 51.4) / 8.7,
    LIMIT_AGE == "21-30" ~ (RAVLT_TOTALSCORE - 49.3) / 8.6,
    LIMIT_AGE == "31-40" ~ (RAVLT_TOTALSCORE - 48.6) / 8,
    LIMIT_AGE == "41-50" ~ (RAVLT_TOTALSCORE - 46.7) / 9.6,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_TOTALSCORE, RAVLT_TOTALSCORE_Z) %>% 
  arrange(ID)

RAVLT_TOTALSCORE_Z



#RAVLT_ALT

RAVLT_ALT_Z <- data %>%
  mutate(RAVLT_ALT_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_ALT - 17.3) / 7.3,
    LIMIT_AGE == "21-30" ~ (RAVLT_ALT - 16.8) / 6.5,
    LIMIT_AGE == "31-40" ~ (RAVLT_ALT - 17.9) / 7,
    LIMIT_AGE == "41-50" ~ (RAVLT_ALT - 16.5) / 7.3,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_ALT, RAVLT_ALT_Z) %>% 
  arrange(ID)




RAVLT_ALT_Z



#RAVLT_RETENTION

RAVLT_RETENTION_Z <- data %>%
  mutate(RAVLT_RETENTION_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_RETENTION - 1) / 0.2,
    LIMIT_AGE == "21-30" ~ (RAVLT_RETENTION - 1) / 0.27,
    LIMIT_AGE == "31-40" ~ (RAVLT_RETENTION - 0.97) / 0.19,
    LIMIT_AGE == "41-50" ~ (RAVLT_RETENTION - 1.01) / 0.34,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_RETENTION, RAVLT_RETENTION_Z) %>% 
  arrange(ID)


RAVLT_RETENTION_Z



#RAVLT_PROAT_INTERFERENCE

RAVLT_PROAT_INTERFERENCE_Z <- data %>%
  mutate(RAVLT_PROAT_INTERFERENCE_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_PROAT_INTERFERENCE - 0.96) / 0.33,
    LIMIT_AGE == "21-30" ~ (RAVLT_PROAT_INTERFERENCE - 0.92) / 0.37,
    LIMIT_AGE == "31-40" ~ (RAVLT_PROAT_INTERFERENCE - 0.91) / 0.33,
    LIMIT_AGE == "41-50" ~ (RAVLT_PROAT_INTERFERENCE - 0.86) / 0.31,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_PROAT_INTERFERENCE, RAVLT_PROAT_INTERFERENCE_Z) %>% 
  arrange(ID)


RAVLT_PROAT_INTERFERENCE_Z




#RAVLT_RETRO_INTERFERENCE

RAVLT_RETRO_INTERFERENCE_Z <- data %>%
  mutate(RAVLT_RETRO_INTERFERENCE_Z = case_when(
    LIMIT_AGE == "18-20" ~ (RAVLT_RETRO_INTERFERENCE - 0.96) / 0.68,
    LIMIT_AGE == "21-30" ~ (RAVLT_RETRO_INTERFERENCE - 0.89) / 0.17,
    LIMIT_AGE == "31-40" ~ (RAVLT_RETRO_INTERFERENCE - 0.94) / 0.74,
    LIMIT_AGE == "41-50" ~ (RAVLT_RETRO_INTERFERENCE - 0.84) / 0.18,

    TRUE ~ NA_real_  # Caso padrão para outras faixas etárias
  )) %>%
  select(ID,RAVLT_RETRO_INTERFERENCE, RAVLT_RETRO_INTERFERENCE_Z) %>% 
  arrange(ID)


RAVLT_RETRO_INTERFERENCE_Z




#BIND COLS E SALVAR

RAVLTs_EscoreZ <- bind_cols(RAVLT_A1_Z, RAVLT_A2_Z, RAVLT_A3_Z, RAVLT_A4_Z, RAVLT_A5_Z,
                            RAVLT_B1_Z, RAVLT_A6_Z, RAVLT_A7_Z, RAVLT_REC_Z, RAVLT_TOTALSCORE_Z,
                           RAVLT_RETENTION_Z, RAVLT_PROAT_INTERFERENCE_Z, RAVLT_RETRO_INTERFERENCE_Z ) 



write.xlsx(RAVLTs_EscoreZ, file = "RAVLTs_EscoreZ.xlsx")




```


```{r Bubble Plots}
library(tibble)
library(readxl)
library(dplyr)
library(gtExtras)
library(ggplot2)
library(plotly)
library(viridis)
library(hrbrthemes)


#setwd("C:/Users/felip/Desktop/R/3_analise")

getwd()

######################################   BPAs Zscore  ###############################

data <- readxl::read_xlsx ("BPAs_EscoreZ.xlsx", sheet = 1)

summary(data)
colnames(data)

data <- data %>% rename(ID = ID...1) %>% select(-ID...8,-ID...11,-ID...14)
  
                                        # Filtrando dados BPAs

p1 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,EDU_LEVEL , AGE, BPA_CONC_POINTS , BPA_CONC_EscoreZ  )

p2 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,EDU_LEVEL, AGE, BPA_DIVID_POINTS , BPA_DIVID_EscoreZ  )

p3 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,EDU_LEVEL ,AGE, BPA_ALTERN_POINTS , BPA_ALTERN_EscoreZ )

ptotal <- data %>%  select(ID,EDU_LEVEL ,GROUP ,EDU_LEVEL ,AGE, BPA_ALTERN_POINTS , BPA_ALTERN_EscoreZ )

                                                #   P1  
  

coresBPA <- c("#1a2887", "#799de4")



p1 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", BPA_CONC_POINTS,
                      "\nZ-Score: ", BPA_CONC_EscoreZ, sep="")) %>%
  ggplot(aes(x = AGE, y = BPA_CONC_EscoreZ, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresBPA) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score Focused Attention", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 18,face = "bold"),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 15),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    
            # Gráfico interativo da bibliotexa ggplottly

pp1 <- ggplotly(p1, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))
  

pp1

                                #   P2

p2 <- data %>%
  arrange(ID) %>%
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", BPA_DIVID_POINTS,
                      "\nZ-Score: ", BPA_DIVID_EscoreZ, sep="")) %>%
  ggplot(aes(x = AGE, y = BPA_DIVID_EscoreZ, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7, position = "jitter") +
  scale_fill_manual(values = coresBPA) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score Divid Attention", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 18,face = "bold"),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 15),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    


                      # Gráfico interativo da bibliotexa ggplottly

pp2 <- ggplotly(p2, tooltip="text") %>%  
 
   layout(legend = list(x = 0, y = 1.01,
                    title = " ",
                    bgcolor = "#ecf0f1",
                    bordercolor = "white",
                    borderwidth = 1,
                    font = list(size = 9, family = "Arial", color = "black"),
                    orientation = 50,
                    tracegroupgap = 20,
                    traceorder = "normal"
                    ))
 
pp2 

                                      #   P3

p3 <- data %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", BPA_ALTERN_POINTS,
                      "\nZ-Score: ", BPA_ALTERN_EscoreZ, sep="")) %>%
  
  ggplot(aes(x = AGE, y = BPA_ALTERN_EscoreZ, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresBPA) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score Altern Attention", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 18,face = "bold"),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 15),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
  

                    # Gráfico interativo da bibliotexa ggplottly

pp3 <-  ggplotly(p3, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp3



                              #BPA_TOTAL

ptotal <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", BPA_TOTAL,
                      "\nZ-Score: ", BPA_TOTAL_EscoreZ, sep="")) %>%
  ggplot(aes(x = AGE, y = BPA_TOTAL_EscoreZ, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresBPA) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score Total", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 18,face = "bold"),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 15),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    
            # Gráfico interativo da bibliotexa ggplottly

pptotal <- ggplotly(ptotal, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))
  

pptotal

######################################    FDTs Zscore  ###############################

data <- readxl::read_excel("FDT_EscoreZ.xlsx")

data <- na.omit(data)

colnames(data)

data <- data %>% rename(ID = ID...1)

data


                                      #  Filtrando FDTs 



p4 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, FDT_READING_TIME , FDT_READING_TIME_Z  )

p5 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, FDT_COUNTING_TIME , FDT_COUNTING_TIME_Z  )

p6 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, FDT_CHOOSING_TIME , FDT_CHOOSING_TIME_Z )

p7 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, FDT_CHANGING_TIME , FDT_CHANGING_TIME_Z )

p8 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, FDT_INHIBITION , FDT_INHIBITION_Z )

p9 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, FDT_FLEXIBILITY , FDT_FLEXIBILITY_Z )




                                            #  P4


coresFDT <- c("#f6a3ab", "#1ab6ac")



p4 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", FDT_READING_TIME,
                      "\nZ-Score: ", FDT_READING_TIME_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = FDT_READING_TIME_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresFDT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score FDT Reading Time", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp4 <- ggplotly(p4, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp4


                                      #  P5

p5 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", FDT_COUNTING_TIME,
                      "\nZ-Score: ", FDT_COUNTING_TIME_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = FDT_COUNTING_TIME_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresFDT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score FDT Counting Time", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp5 <- ggplotly(p5, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp5


                                      #  P6


p6 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", FDT_CHOOSING_TIME,
                      "\nZ-Score: ", FDT_CHOOSING_TIME_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = FDT_CHOOSING_TIME_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresFDT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score FDT Chossing Time", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp6 <- ggplotly(p6, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp6


                                      # P7


p7<- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", FDT_CHANGING_TIME,
                      "\nZ-Score: ", FDT_CHANGING_TIME_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = FDT_CHANGING_TIME_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresFDT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score FDT Changing Time", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp7 <- ggplotly(p7, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp7


                                      # P8


p8<- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", FDT_INHIBITION,
                      "\nZ-Score: ", FDT_INHIBITION_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = FDT_INHIBITION_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresFDT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score FDT Inbition", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )

pp8 <- ggplotly(p8, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp8


                                    #   P9

p9<- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", FDT_FLEXIBILITY,
                      "\nZ-Score: ", FDT_FLEXIBILITY_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = FDT_FLEXIBILITY_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresFDT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score FDT Flexibility", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp9 <- ggplotly(p9, tooltip="text") %>%
  
  layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp9
######################################    RAVLTs Zscore  ###############################


data <- readxl::read_xlsx ("RAVLTs_EscoreZ.xlsx")

data

data <- data %>% dplyr::rename(ID = ID...1)

                                        # Filtrando RAVLTs 



p10 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_A1 , RAVLT_A1_Z  )

p11 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_A2 , RAVLT_A2_Z  )

p12 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_A3 , RAVLT_A3_Z )

p13 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_A4 , RAVLT_A4_Z )

p14 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_A5 , RAVLT_A5_Z )

p15 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_B1 , RAVLT_B1_Z )

p16 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_A6 , RAVLT_A6_Z )

p17 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_A7 , RAVLT_A7_Z )

p18 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_TOTALSCORE , RAVLT_TOTALSCORE_Z )

p19 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_REC , RAVLT_REC_Z )

p20 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_RETENTION , RAVLT_RETENTION_Z )

p21 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_PROAT_INTERFERENCE , RAVLT_PROAT_INTERFERENCE_Z )

p22 <- data %>%  select(ID,EDU_LEVEL ,GROUP ,AGE, RAVLT_RETRO_INTERFERENCE , RAVLT_RETRO_INTERFERENCE_Z )




                                      # P10


coresRAVLT<- c("#7f1c2b", "#9c9ce9")



p10 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_A1,
                      "\nZ-Score: ", RAVLT_A1_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_A1_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT A1", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    


pp10 <- ggplotly(p10, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp10

                                    # P11


p11 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_A2,
                      "\nZ-Score: ", RAVLT_A2_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_A2_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT A2", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp11 <- ggplotly(p11, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp11



                            # P12


p12 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_A3,
                      "\nZ-Score: ", RAVLT_A3_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_A3_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT A3", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp12 <- ggplotly(p12, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp12


                                # P13


p13 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_A4,
                      "\nZ-Score: ", RAVLT_A4_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_A4_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT A4", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )


pp13 <- ggplotly(p13, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp13


                                  #  P14


p14 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_A5,
                      "\nZ-Score: ", RAVLT_A5_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_A5_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT A4", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp14 <- ggplotly(p14, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp14


                                # P15


p15 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_B1,
                      "\nZ-Score: ", RAVLT_B1_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_B1_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT B1", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp15 <- ggplotly(p15, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp15



                              #  P16


p16 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_A6,
                      "\nZ-Score: ", RAVLT_A6_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_A6_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT A6", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp16 <- ggplotly(p16, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp16



                                  #  P17

p17 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_A7,
                      "\nZ-Score: ", RAVLT_A7_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_A7_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT A7", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp17 <- ggplotly(p17, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp17

                                      # P18

p18 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_TOTALSCORE,
                      "\nZ-Score: ", RAVLT_TOTALSCORE_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_TOTALSCORE_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT Total Score", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp18 <- ggplotly(p18, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp18



                                    # P19

p19 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_TOTALSCORE,
                      "\nZ-Score: ", RAVLT_TOTALSCORE_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_TOTALSCORE_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT Total Score", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp19 <- ggplotly(p19, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp19


                                  # P20

p20 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_RETENTION,
                      "\nZ-Score: ", RAVLT_RETENTION_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_RETENTION_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT Retention", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    


pp20 <- ggplotly(p20, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))


pp20


                                    # P21

p21 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_PROAT_INTERFERENCE,
                      "\nZ-Score: ", RAVLT_PROAT_INTERFERENCE_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_PROAT_INTERFERENCE_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT Proative Interference", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp21 <- ggplotly(p21, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp21


                                      #  P22

p22 <- data %>% 
  arrange(ID) %>% 
  mutate(text = paste("Identification: ", ID , "\nAge: ", AGE , 
                      "\nPoints: ", RAVLT_RETRO_INTERFERENCE,
                      "\nZ-Score: ", RAVLT_RETRO_INTERFERENCE_Z, sep="")) %>%
  ggplot(aes(x = AGE, y = RAVLT_RETRO_INTERFERENCE_Z, fill= GROUP, stroke = 0,
             size = AGE, shape = EDU_LEVEL , text = text)) +
  geom_point(alpha = 0.7,position = "jitter") +
  scale_fill_manual(values = coresRAVLT) +
  scale_size(range = c(2, 5)) +
  scale_x_continuous(name = "Age", limits = c(10, 52), breaks = seq(10, 50, by = 10)) +
  scale_y_continuous(name = "Z Score", limits = c(-3, 3), breaks = seq(-3, 3)) +
  geom_hline(yintercept = -3:3, color = "black", alpha = 0.1) + 
  geom_hline(yintercept = 0, color = "red", alpha = 0.3, linetype = "") +
  labs(y = "Y", title = "Z Score RAVLT Retroative Interference", shape= "", size = "") +
  theme_classic() +
  
    theme(
      text = element_text(family = "Arial Narrow", size = 11.5),
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12),
    plot.caption = element_text(size = 9, face = "italic"),
    axis.title = element_text(size = 10),
    legend.position = "",
    legend.text = element_text(size = 5)
    )
    

pp22 <- ggplotly(p22, tooltip="text") %>%  
  
    layout(legend = list(x = 0, y = 1.01,
                     title = " ",
                     bgcolor = "#ecf0f1",
                     bordercolor = "white",
                     borderwidth = 1,
                     font = list(size = 9, family = "Arial", color = "black"),
                     orientation = 50,
                     tracegroupgap = 20,
                     traceorder = "normal"
                     ))

pp22


```



```{r Curva de Crescimento}

#install.packages('reshape2')
library(ggplot2)
library(dplyr)
library(readxl)
library(reshape2)

getwd()


df <- read_excel("RAVLTs_EscoreZ.xlsx")

colnames(df)

#1a2887, #799de4

###################################### Regressão Linear   ##########################################

df.RAVLTs <- df %>% select(GROUP,AGE,RAVLT_A1,RAVLT_A2,RAVLT_A3,RAVLT_A4,RAVLT_A5)


df.melted <- melt(df.RAVLTs, id.vars = c("AGE", "GROUP"), variable.name = "Variável", value.name = "Pontuação")

cores <- c("CASE" = "#1a2887", "CONTROL" = "#799de4")

# Criar o gráfico de linhas
p <- ggplot(df.melted, aes(x = AGE, y = Pontuação, color = GROUP)) +
  geom_point(alpha=0.5, position = "jitter", size = 1.5) +
  stat_smooth( method = "lm", span = 0.8, se = F)+
  labs(title = "Gráfico de Linhas RAVLT por Grupo",
       x = "AGE",
       y = "Pontuação RAVLT",
       color = "Grupos") +
  scale_color_manual(values = cores) +
  facet_wrap(~ Variável, scales = "free_y", nrow = 1) +  # Separação por GROUP (caso e controle)
  theme_minimal()

p

shapiro.test(df.RAVLTs$RAVLT_A5)


ggsave(filename = "REGRESSAO-RAVLTs.pdf", plot = p, width = 14, height = 10)

```
```{r Line Plot}
############################## Médias de Desempenho por Idade #################
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyr)

getwd()

data.ravlt <- read_excel("RAVLTs_EscoreZ.xlsx")

data.ravlt <- data.ravlt %>%  select("AGE","GROUP","RAVLT_A1","RAVLT_A2", "RAVLT_A3","RAVLT_A4", "RAVLT_A5")
                            

data.ravlt <- data.ravlt %>%
  mutate(
    faixa_etaria = case_when(
      AGE >= 18 & AGE <= 20 ~ "18-20",
      AGE >= 21 & AGE <= 30 ~ "21-30",
      AGE >= 21 & AGE <= 30 ~ "21-30",
      AGE >= 31 & AGE <= 40 ~ "31-40",
      AGE >= 41 & AGE <= 50 ~ "41-50",
      TRUE ~ NA_character_
    )
  )

medias_ravlt <- data.ravlt %>%
  group_by(GROUP, faixa_etaria) %>%
  summarise(
    media_RAVLT_A1 = mean(RAVLT_A1, na.rm = TRUE),
    media_RAVLT_A2 = mean(RAVLT_A2, na.rm = TRUE),
    media_RAVLT_A3 = mean(RAVLT_A3, na.rm = TRUE),
    media_RAVLT_A4 = mean(RAVLT_A4, na.rm = TRUE),
    media_RAVLT_A5 = mean(RAVLT_A5, na.rm = TRUE)
  ) %>%
  ungroup()


medias_ravlt

medias_ravlt <- data.ravlt %>%
  group_by(GROUP, faixa_etaria) %>%
  summarise(
    media_RAVLT_A1 = mean(RAVLT_A1, na.rm = TRUE),
    media_RAVLT_A2 = mean(RAVLT_A2, na.rm = TRUE),
    media_RAVLT_A3 = mean(RAVLT_A3, na.rm = TRUE),
    media_RAVLT_A4 = mean(RAVLT_A4, na.rm = TRUE),
    media_RAVLT_A5 = mean(RAVLT_A5, na.rm = TRUE),
    sd_RAVLT_A1 = sd(RAVLT_A1, na.rm = TRUE),
    sd_RAVLT_A2 = sd(RAVLT_A2, na.rm = TRUE),
    sd_RAVLT_A3 = sd(RAVLT_A3, na.rm = TRUE),
    sd_RAVLT_A4 = sd(RAVLT_A4, na.rm = TRUE),
    sd_RAVLT_A5 = sd(RAVLT_A5, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  pivot_longer(cols = starts_with("media_"), names_to = "RAVLT", values_to = "media") %>%
  pivot_longer(cols = starts_with("sd_"), names_to = "sd_name", values_to = "sd") %>%
  mutate(RAVLT = gsub("media_", "", RAVLT),
         sd_name = gsub("sd_", "", sd_name)) %>%
  filter(RAVLT == sd_name) %>%
  select(-sd_name)



p <- ggplot(medias_ravlt, aes(x = faixa_etaria, y = media, group = interaction(GROUP, RAVLT), color = RAVLT)) +
  geom_line(aes(linetype = GROUP), size = 1) +  # Diferencia os grupos por tipo de linha
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = media - sd, ymax = media + sd, fill = RAVLT), alpha = 0.2) +
  scale_color_manual(values = c("#01204E", "#028391", "#FF0000", "#FFA27F", "#E59BE9")) +  # Paleta de cores gradiente para RAVLT
  scale_linetype_manual(values = c("solid", "dashed")) +  # Tipos de linha para os grupos
  labs(title = "Médias dos Valores RAVLT por Grupo e Faixa Etária",
       x = "Faixa Etária",
       y = "Média dos Valores RAVLT",
       color = "RAVLT",
       linetype = "Grupo") +
  theme_minimal()

p


# Criar o gráfico de linha com sombra para desvio padrão e facet_wrap
p <- ggplot(medias_ravlt, aes(x = faixa_etaria, y = media, group = GROUP, color = GROUP)) +
  geom_errorbar(aes(ymin = media - sd, ymax = media + sd, fill = GROUP), alpha = 0.6) +
  geom_line(aes(linetype = GROUP), size = 1) +  # Diferencia os grupos por tipo de linha
  geom_point(size = 2) +
  facet_wrap(~ RAVLT, scales = "free_y") +  # Faceta por variável RAVLT
  scale_linetype_manual(values = c("solid", "dashed")) +  # Tipos de linha para os grupos
  scale_y_continuous(limits = c(0, 15)) +  # Ajustar a escala do eixo y
  labs(title = "Médias dos Valores RAVLT por Grupo e Faixa Etária",
       x = "Faixa Etária",
       y = "Média dos Valores RAVLT",
       color = "Grupo",
       fill = "Grupo",
       linetype = "Grupo") +
  theme_minimal()


p


ggsave(filename = "RAVLTs-A1-A5.pdf", plot = p)

```

```{r}
# comparando de 5 em 5 

data.ravlt <- read_excel("RAVLTs_EscoreZ.xlsx")

data.ravlt <- data.ravlt %>%  select("AGE","GROUP","RAVLT_A1","RAVLT_A2", "RAVLT_A3","RAVLT_A4", "RAVLT_A5")
 

data.ravlt <- data.ravlt %>%
  mutate(
    faixa_etaria = case_when(
      AGE >= 18 & AGE <= 20 ~ "18-20",
      AGE >= 21 & AGE <= 25 ~ "21-25",
      AGE >= 26 & AGE <= 30 ~ "26-30",
      AGE >= 31 & AGE <= 35 ~ "31-35",
      AGE >= 36 & AGE <= 40 ~ "36-40",
      AGE >= 41 & AGE <= 45 ~ "41-45",
      AGE >= 46 & AGE <= 50 ~ "46-50"
    )
  )

#medias_ravlt <- data.ravlt %>%
#  group_by(GROUP, faixa_etaria) %>%
#  summarise(
#    media_RAVLT_A1 = mean(RAVLT_A1, na.rm = TRUE),
#    media_RAVLT_A2 = mean(RAVLT_A2, na.rm = TRUE),
#    media_RAVLT_A3 = mean(RAVLT_A3, na.rm = TRUE),
#    media_RAVLT_A4 = mean(RAVLT_A4, na.rm = TRUE),
#    media_RAVLT_A5 = mean(RAVLT_A5, na.rm = TRUE)
#  ) %>%
#  ungroup()

#medias_ravlt

medias_ravlt <- data.ravlt %>%
  group_by(GROUP, faixa_etaria) %>%
  summarise(
    media_RAVLT_A1 = mean(RAVLT_A1, na.rm = TRUE),
    media_RAVLT_A2 = mean(RAVLT_A2, na.rm = TRUE),
    media_RAVLT_A3 = mean(RAVLT_A3, na.rm = TRUE),
    media_RAVLT_A4 = mean(RAVLT_A4, na.rm = TRUE),
    media_RAVLT_A5 = mean(RAVLT_A5, na.rm = TRUE),
    sd_RAVLT_A1 = sd(RAVLT_A1, na.rm = TRUE),
    sd_RAVLT_A2 = sd(RAVLT_A2, na.rm = TRUE),
    sd_RAVLT_A3 = sd(RAVLT_A3, na.rm = TRUE),
    sd_RAVLT_A4 = sd(RAVLT_A4, na.rm = TRUE),
    sd_RAVLT_A5 = sd(RAVLT_A5, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  pivot_longer(cols = starts_with("media_"), names_to = "RAVLT", values_to = "media") %>%
  pivot_longer(cols = starts_with("sd_"), names_to = "sd_name", values_to = "sd") %>%
  mutate(RAVLT = gsub("media_", "", RAVLT),
         sd_name = gsub("sd_", "", sd_name)) %>%
  filter(RAVLT == sd_name) %>%
  select(-sd_name)



# Criar o gráfico de linha com sombra para desvio padrão e facet_wrap
p <- ggplot(medias_ravlt, aes(x = faixa_etaria, y = media, group = GROUP, color = GROUP)) +
  geom_errorbar(aes(ymin = media - sd, ymax = media + sd, fill = GROUP), alpha = 0.6) +
  geom_line(aes(linetype = GROUP), size = 1) +  # Diferencia os grupos por tipo de linha
  geom_point(size = 2) +
  facet_wrap(~ RAVLT, scales = "free_y") +  # Faceta por variável RAVLT
  scale_linetype_manual(values = c("solid", "dashed")) +  # Tipos de linha para os grupos
  scale_y_continuous(limits = c(0, 15)) +  # Ajustar a escala do eixo y
  labs(title = "Médias dos Valores RAVLT por Grupo e Faixa Etária",
       x = "Faixa Etária",
       y = "Média dos Valores RAVLT",
       color = "Grupo",
       fill = "Grupo",
       linetype = "Grupo") +
  theme_minimal()

p

ggsave(filename = "RAVLTs-regresssao-subdividida.pdf", plot = p , width = 14, height = 10)



```


